name: Linux GitHub CI

on:   
  push:
    branches: [prod, dev-*]
  pull_request:
    branches: [prod]


env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Xmx512m -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS
  TAKARI_SMART_BUILDER_VERSION: 0.6.1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 8
    steps:
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "dir/fileName.txt"
        FILE_DATA: "file content"
    
    - name: create maven artifacts
      uses: actions/upload-artifact@v2
      with:
        name: create war file
        path: dir/fileName.txt
        
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::664974615300:role/github-s3-copy-role
        role-session-name: GithubActionDeployment
        aws-region: ap-southeast-2
        
    - name: Copy development war to S3 bucket 
      run: |
        aws s3 cp dir/fileName.txt s3://inapp-war-files/${BRANCH}/
      if: startsWith(github.ref, 'refs/heads/dev-')
      env:
        BRANCH: "nonprod"
        
    - name: Copy production war to S3 bucket 
      run: |
        aws s3 cp dir/fileName.txt s3://inapp-war-files/${BRANCH}/
      if: github.ref == 'refs/heads/prod'
      env:
        BRANCH: "prod"  
        
